-- MySQL Script generated by MySQL Workbench
-- Thu 14 Apr 2016 01:41:50 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema apab
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema apab
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `apab` DEFAULT CHARACTER SET utf8 ;
USE `apab` ;

-- -----------------------------------------------------
-- Table `apab`.`events`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apab`.`events` ;

CREATE TABLE IF NOT EXISTS `apab`.`events` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `live` INT(11) NOT NULL DEFAULT '0' COMMENT '',
  `default_opt_type` VARCHAR(45) NOT NULL DEFAULT 'GENLIKE' COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `apab`.`options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apab`.`options` ;

CREATE TABLE IF NOT EXISTS `apab`.`options` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `type` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `option` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `apab`.`audience_resp`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apab`.`audience_resp` ;

CREATE TABLE IF NOT EXISTS `apab`.`audience_resp` (
  `idaudience_resp` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `event_id` INT(11) NOT NULL COMMENT '',
  `opt_id` INT(11) NOT NULL COMMENT '',
  `opt_type` VARCHAR(45) NOT NULL COMMENT '',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `agent` VARCHAR(100) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `slideno` INT(11) NULL DEFAULT NULL COMMENT '',
  `ip` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  `seatno` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NULL DEFAULT NULL COMMENT '',
  PRIMARY KEY (`idaudience_resp`, `event_id`, `opt_id`)  COMMENT '',
  INDEX `fk_audience_resp_events_idx` (`event_id` ASC)  COMMENT '',
  INDEX `fk_audience_resp_options1_idx` (`opt_id` ASC)  COMMENT '',
  CONSTRAINT `fk_audience_resp_events`
    FOREIGN KEY (`event_id`)
    REFERENCES `apab`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_audience_resp_options1`
    FOREIGN KEY (`opt_id`)
    REFERENCES `apab`.`options` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `apab`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apab`.`status` ;

CREATE TABLE IF NOT EXISTS `apab`.`status` (
  `id` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `event_id` INT(11) NOT NULL COMMENT '',
  `opt_type` VARCHAR(45) NOT NULL COMMENT '',
  `slideno` INT(11) NOT NULL COMMENT '',
  `path` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_unicode_ci' NOT NULL COMMENT '',
  `time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  PRIMARY KEY (`id`, `event_id`)  COMMENT '',
  INDEX `fk_status_events1_idx` (`event_id` ASC)  COMMENT '',
  CONSTRAINT `fk_status_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `apab`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
COMMENT = 'current status';


-- -----------------------------------------------------
-- Table `apab`.`winevents`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `apab`.`winevents` ;

CREATE TABLE IF NOT EXISTS `apab`.`winevents` (
  `idwinevents` INT(11) NOT NULL AUTO_INCREMENT COMMENT '',
  `event_id` INT(11) NOT NULL COMMENT '',
  `timestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  `agent` VARCHAR(100) NOT NULL COMMENT '',
  `ip` VARCHAR(45) NOT NULL COMMENT '',
  `seatno` VARCHAR(45) NOT NULL COMMENT '',
  `winevent` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`idwinevents`, `event_id`)  COMMENT '',
  INDEX `fk_winevents_events1_idx` (`event_id` ASC)  COMMENT '',
  CONSTRAINT `fk_winevents_events1`
    FOREIGN KEY (`event_id`)
    REFERENCES `apab`.`events` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
